modLoader="javafml"
loaderVersion="[36,)"
license="LGPL v2.1"

[[mods]]
    modId="assortedspells"
    displayName="Book of Assorted Spells"
    description='''
    Adds a variety of spells to Minecraft.
    '''
    version="${file.jarVersion}"
    authors="Red_X_Tornado, EnderTurret"

[[dependencies.assortedspells]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.assortedspells]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"